export const FETCH_USER_DATA_SUCCESS = 'FETCH_USER_DATA_SUCCESS';

export const SEND_USER_DATA_SUCCESS = 'SEND_USER_DATA_SUCCESS';

export const THROW_AUTHENTICATION_ERROR = 'THROW_AUTHENTICATION_ERROR';

export const USER_IS_LOGGED_OUT = 'USER_IS_LOGGED_OUT';
