export const FETCH_USER_DATA_SUCCESS = 'FETCH_USER_DATA_SUCCESS';

export const SEND_USER_DATA_SUCCESS = 'SEND_USER_DATA_SUCCESS';

export const CHANGE_USER_DATA_SUCCESS = 'CHANGE_USER_DATA_SUCCESS';

export const SEND_REMOVE_REQUEST_SUCCESS = 'SEND_REMOVE_REQUEST_SUCCESS';

export const THROW_AUTHENTICATION_ERROR = 'THROW_AUTHENTICATION_ERROR';

export const FETCH_FILMS_DATA_SUCCESS = 'FETCH_FILMS_DATA_SUCCESS';

export const FETCH_USERS_DATA_SUCCESS = 'FETCH_USERS_DATA_SUCCESS';

export const REMOVE_USERS_SUCCESS = 'REMOVE_USERS_SUCCESS';

export const USER_IS_LOGGED_OUT = 'USER_IS_LOGGED_OUT';
